xfortran: update compiler version
conda-forge/conda-forge-pinning-feedstock pull request #1359
Opened 2021-03-20 19:57 UTC by xoviat

2021-03-20 19:57 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-03-20 19:59 UTC, xoviat commented
note migration.yml similar to https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/837/files may be required.

2021-03-20 20:00 UTC, beckermr requested changes
This change will need to be discussed with @conda-forge/core and probably requires a migration.

2021-03-20 20:01 UTC, xoviat commented
it's been pending for a while now, and wasn't done. I thought I'd shake things loose.

2021-03-20 20:03 UTC, isuruf commented
Yes, I don't think there's anything to discuss, but we do need a migration yaml.

2021-03-20 20:06 UTC, xoviat commented
Is this okay?

2021-03-20 20:07 UTC, beckermr commented on recipe/conda_build_config.yaml
> +  - 11.0.1                     # [win64]
Remove this change until the migration is done.

2021-03-20 20:09 UTC, beckermr commented on recipe/migrations/flang110.yml
> +  override_cbc_keys:
```suggestion
  longterm: True
  override_cbc_keys:
```

2021-03-20 20:27 UTC, beckermr commented
@conda-forge/core Do we want to make an announcement? Should we ship both versions for a while?

2021-03-23 02:40 UTC, jakirkham commented
Friendly nudge @conda-forge/core (since this came in on the weekend people may have missed it)

2021-07-06 14:08 UTC, xoviat commented
cc @h-vetinari

2021-07-06 15:43 UTC, isuruf commented
We still need to add an option to the bot to send this PRs to only packages which use flang on windows. I think right now the bot will send a PR to packages that use fortran on unix, but use `m2w64-gcc` on windows too.

cc @conda-forge/bot

2021-10-12 10:41 UTC, h-vetinari commented
Would be awesome if this can be picked up again. 🙃

2022-02-03 13:00 UTC, zklaus commented
> We still need to add an option to the bot to send this PRs to only packages which use flang on windows. I think right now the bot will send a PR to packages that use fortran on unix, but use `m2w64-gcc` on windows too.
> 
> cc @conda-forge/bot

@isuruf, any hint on how to do that? I might give it a shot.

2022-02-03 13:21 UTC, beckermr commented
How many windows flang packages are there? Maybe we rebuild a few extra ones if it is small?

2022-02-03 19:00 UTC, jakirkham commented
How many Fortran packages are there? And how many of those support Windows? Guessing this is probably quite small, but don't really know.

2022-02-04 10:47 UTC, zklaus commented
@beckermr, @jakirkham, are you saying that we don't need to modify the bot per @isuruf's suggestion, just because even if this would happen (i.e. some packages get superfluous PRs), those are likely so few that we can deal with them just by manually closing the PRs?

Hence, this migrator can be started as is?

2022-02-04 12:06 UTC, beckermr commented
That is my suggestion yes. We'll need everyone to agree before we go that way. I also could be wrong.

2022-02-04 12:12 UTC, isuruf commented
No. There's 300+ fortran feedstocks and only about 2 dozen feedstocks using flang. I wouldn't characterize that as `likely so few`.

2022-02-04 12:16 UTC, beckermr commented
Ok. So then we’ll need a pr to the bot to avoid rebuilding about 30 feedstocks out of 300. I don’t think I’ll have time to do this but I’m happy to review!

2022-02-04 12:24 UTC, isuruf commented
> So then we’ll need a pr to the bot to avoid rebuilding about 30 feedstocks out of 300

No, it's the other way around. We have to avoid rebuilding 270 out of 300.

2022-02-04 12:28 UTC, zklaus commented
Gotcha. Do I understand correctly that this needs a PR to change [`auto_tick.py`](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/auto_tick.py)?

@isuruf, did you have something general in mind, like an addition to the yaml format for the migrators that allows filtering on the graph, or rather something specific, more like a [custom migrator](https://regro.github.io/cf-scripts/migrators.html#custom-migrations)?

2022-02-04 12:32 UTC, beckermr commented
> No, it's the other way around. We have to avoid rebuilding 270 out of 300.

Ahh. I am still not terribly worried about that. 

As for the bot, we likely want to add a platform filtering option to the standard yaml migratory here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/migration_yaml.py#L113

Then we can list the platforms to target and avoid a custom migrator.

2022-02-04 12:34 UTC, zklaus commented
I'll see what I can do. But if anybody else gets to it before me, I won't be mad :stuck_out_tongue:.

2022-04-11 03:20 UTC, h-vetinari commented
@zklaus any news on your efforts with this? 🙃

2022-04-11 12:18 UTC, zklaus commented
Sorry, @h-vetinari, I have been taken up by other things. I am not sure when I will manage to pick this up in earnest.

2023-04-18 06:04 UTC, h-vetinari commented
With llvm-flang hopefully not toooooo far out, I gave this a shot in https://github.com/regro/cf-scripts/pull/1655. Feedback & advice appreciated!

2023-04-18 22:51 UTC, h-vetinari reviewed
@xoviat, not sure if you're still around? 😅 

If yes, could you try to add the following (based on https://github.com/regro/cf-scripts/pull/1655)? Since we couldn't write tests I'm a bit apprehensive if it'll work right away, but we can always pause & debug the migration.

PS. Not sure if relevant; clang 11.0 had an ABI break and 11.1 was released to fix it. I had an open [PR](https://github.com/conda-forge/flang-feedstock/pull/24) to rebuild flang for that, but this ran into some weird build tooling errors I wasn't able to debug at the time.

2023-04-18 22:51 UTC, h-vetinari commented on recipe/migrations/flang110.yml
> +  longterm: True
```suggestion
  longterm: True
  platform_allowlist:
    - win-64
```

2023-05-03 23:56 UTC, h-vetinari commented
@isuruf, are your concerns about the migration now addressed? I believe the very old default flang version is the reason why the compilers package is having resolution problems: https://github.com/conda-forge/compilers-feedstock/issues/58

2023-11-01 07:28 UTC, h-vetinari commented
As an update to anyone subscribed here - we discussed this in a core meeting a few months [ago](https://github.com/conda-forge/conda-forge.github.io/blob/main/src/orga/minutes/2023-06-28.md), and the status was that the "updated" flang 11 builds based on classic-flang have no support (we also haven't heard from @xoviat for a long time), and so we decided to wait for llvm-flang to materialise.

We now have flang 17 live in conda-forge, but it's still somewhat experimental, so the earliest to retry this realistically is for flang 18 early next year.

2024-07-08 23:30 UTC, h-vetinari commented
Another update: flang 18 didn't work for compiling OpenBLAS on windows, but with the in-progress flang 19 (ETA ~September), things are looking much [better](https://github.com/conda-forge/openblas-feedstock/pull/115#issuecomment-2215517076).

2024-08-04 09:31 UTC, h-vetinari commented
This is still a draft, but it's looking like flang 19 will finally be ready on windows to compile most of our feedstocks. Already tested successfully: OpenBLAS, SciPy and a few others in progress.

2024-10-10 10:41 UTC, h-vetinari commented
Finally the rename from flang-new to flang landed: https://github.com/llvm/llvm-project/commit/06eb10dadfaeaadc5d0d95d38bea4bfb5253e077 🥳 

I've tried backporting the patch to LLVM 19, and aside from some trivial conflicts, it looks like we could do it, though I think I'd prefer to leave that for LLVM 20. Let me know if someone thinks differently...

2024-10-12 05:35 UTC, h-vetinari commented
Alright, let's get this party started!

2024-10-12 05:35 UTC, merged

2024-10-14 22:23 UTC, beckermr reviewed
Well I totally missed this, but the migration files need to end in `.yaml`. We should add a test and/or hook in pre-commit for this.