Add all buildable packages to osx-arm64
conda-forge/conda-forge-pinning-feedstock pull request #2436
Opened 2022-01-24 14:43 UTC by jonashaag

This adds all packages to osx-arm64 that I was able to build on my M1 machine without modifications.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-01-24 14:43 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2022-01-24 14:49 UTC, jaimergp commented
Oh wow, thanks for the effort! I wonder though if this amount of packages can functionally DoS our bot?

2022-01-24 14:57 UTC, beckermr requested changes
The bot will do fine, but we cannot merge this. 

Moving recipes over to the M1 is a burden on our maintainers and our cross-compiling architecture. Even if it builds natively, things can fail when cross-compiling. 

Please add only what you need.

2022-01-24 15:11 UTC, jonashaag commented
How about I attempt to cross-compile all of those packages and keep only the ones that cross-compile without modification?

2022-01-24 15:20 UTC, xhochy commented
> How about I attempt to cross-compile all of those packages and keep only the ones that cross-compile without modification?

That would be better but still quite some burden on the maintainers and quite informative. I would expect many of them to fail. Keeping this list down to things you really need is much better (even better if you also step in as the maintainer of some of these packages).

2022-01-24 15:26 UTC, wolfv commented
Just FYI before attempting to cross compile -- there is some "magic" somewhere in the bot that modifies the `build.sh` scripts slightly (e.g. injecting `${CMAKE_ARGS}` for cmake, or autotools reconf and things like this.  Also `cross_python` sometimes is automatically added to teh `host` dependencies. 
Unfortunately I can't tell you exactly where that source is and how you could use it.

2022-01-24 15:27 UTC, jonashaag commented
My motivation for this was that some M1 users (most, actually) don't know how to build Conda packages for M1. Not even simply adding the packages to this repo. What would be a way forward to help those people, in a way that doesn't put too much burden on the Conda-forge maintainers?

2022-01-24 15:44 UTC, xhochy commented
> Just FYI before attempting to cross compile -- there is some "magic" somewhere in the bot that modifies the `build.sh` scripts slightly (e.g. injecting `${CMAKE_ARGS}` for cmake, or autotools reconf and things like this. Also `cross_python` sometimes is automatically added to teh `host` dependencies. Unfortunately I can't tell you exactly where that source is and how you could use it.

Most of them are in https://github.com/regro/cf-scripts/blob/449368112dd90c4155934b526475aa9065647b86/conda_forge_tick/migrators/cross_compile.py#L1

2022-01-24 15:46 UTC, xhochy commented
> My motivation for this was that some M1 users (most, actually) don't know how to build Conda packages for M1. Not even simply adding the packages to this repo. What would be a way forward to help those people, in a way that doesn't put too much burden on the Conda-forge maintainers?

1. Definitely try out whether cross-compilation works.
2. Do it by popularity, do it in small chunks.
3. First check the graph in https://conda-forge.org/status/#armosxaddition The packages in that graph are ones that were requested but don't build yet. These actually provide the highest value.

2022-01-25 13:49 UTC, jonashaag commented
List of packages that can be cross-compiled, top 100 by number of downloads:

```
pandoc
enum34
backports.weakref
pathlib
quaternion
billiard
kombu
gensim
pycurl
compas
bitarray
newrelic
luigi
trio_asyncio
profilehooks
humanfriendly
ptvsd
nipype
wrf-python
pyomo
mrjob
fs
jpype1
xlwings
python-chromedriver-binary
cmd2
iteration_utilities
python-crfsuite
implicit
mysql-connector-python
jcc
pigz
pre_commit
elasticsearch-dsl
clickhouse-driver
apscheduler
aliyun-python-sdk-core
cherrypy
wordcloud
libsass
mpl_sample_data
falcon
promise
sagemaker-python-sdk
backports.os
hpc05
frozendict
doconce
cx_oracle
python-annoy
cchardet
thriftpy2
flask-restplus
inflect
mdanalysis
flask-restalchemy
kuyruk
oslo.config
fastrlock
blessings
pygram11
docker-compose
skein
sanic
adaptive
dpath
filebutler
pyvisa
sasl
plumpy
python-lzo
rebound
ciso8601
py-lz4framed
compas_fab
radical.pilot
pycares
schema-salad
azure-storage
naima
brian2
jupyter_dashboards
mongoengine
validictory
aws-parallelcluster
pyomo.extras
conda-wrappers
pymssql
anypytools
cis
wsproto
biotite
mercurial
pyahocorasick
sos-notebook
resonance
pytmatrix
py-ubjson
pyflann
zodbpickle
```

There are definitely some false-positives in there, eg. Pandoc, enum34 (archived).

2022-01-25 13:56 UTC, beckermr commented
Thanks for this. If you actually use any of those packages, please submit them in a new PR.

2022-02-05 03:20 UTC, ngam commented
Damn... it would'a been fun to see how merging this PR would'a unfolded 😆 

@beckermr what's the endgame for these migrations usually? Does the bot have an expiration date where it goes all out or does keep going drip drip drip drip drip ad infinitum?

2022-02-05 03:51 UTC, beckermr commented
For a migration like this we’ll just let it go forever. If we ever get enough CI support, we’ll likely build packages natively and turn on OS X arm by default. It’ll be at least a year for that or more is my guess.

2022-02-05 03:56 UTC, ngam commented
> For a migration like this we’ll just let it go forever. If we ever get enough CI support, we’ll likely build packages natively and turn on OS X arm by default. It’ll be at least a year for that or more is my guess.

A matter of time, we will definitely get CI support

I do wonder if the conda-forge community should petition Apple directly for some support, maybe they'd be so generous to give us something like this https://developer.apple.com/xcode-cloud/ (no way in hell would Apple do such a thing in general lol, but maybe if fundamentally tweak how we build osx stuff...)

2022-04-05 20:38 UTC, manics commented
Successfully building and publishing an osx-arm64 package doesn't mean it's correct, as I've unfortunately just discovered :cry:.
The zeroc-ice osx-arm64 migration PR built successfully and I merged it, but the arm64 package contained x86_64 libraries:
https://github.com/conda-forge/zeroc-ice-feedstock/pull/20#issuecomment-1087954281

This is due the upstream package `setup.py` containing
```py
if platform == 'darwin':
    if not 'ARCHFLAGS' in os.environ:
        os.environ['ARCHFLAGS'] = '-arch x86_64'
```
I'm testing a fix for that here https://github.com/conda-forge/zeroc-ice-feedstock/pull/25

2022-04-05 20:44 UTC, BastianZim commented
Yes, unfortunately the _osx-arm64_ packages are only built but not tested right now: https://conda-forge.org/docs/maintainer/conda_forge_yml.html#test

2022-04-06 13:45 UTC, beckermr commented
cc @conda-forge/core @isuruf Should we write this into the conda build checks?

2025-10-23 15:44 UTC, h-vetinari commented
Was interested how much of this we've already done explicitly. We went from

<img width="178" height="62" alt="image" src="https://github.com/user-attachments/assets/8a27e001-2c2d-4d24-b415-21f0548b0db8" />

to

<img width="182" height="77" alt="image" src="https://github.com/user-attachments/assets/006c9127-f967-45aa-8672-f142e7e51b76" />

Though likely more of those are done as transitive dependencies of other packages already listed in `osx_arm64.txt`

2026-07-14 15:27 UTC, xhochy commented
Closing this as stale. We will probably roll-out osx-arm64 in a different fashion.

2026-07-14 15:27 UTC, closed without merging