Bump `netcdf-fortran` pin to 4.6
conda-forge/conda-forge-pinning-feedstock pull request #4703
Opened 2023-07-22 02:08 UTC by SimonBoothroyd

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

It looks like the current pins are trying to restrict to `netcdf-fortran =4.5` and `libnetcdf =4.9.2`, but `netcdf-fortran =4.5` looks like it is itself [restricted to `libnetcdf =4.8`](https://anaconda.org/conda-forge/netcdf-fortran/files?page=2) leading to [unresolvable environments](https://github.com/conda-forge/staged-recipes/pull/23435#issuecomment-1646185849).

It looks like a [migration to `4.6`](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3185) was merged but the pin was never bumped. @xylar @ocefpaf was this intentional?

Apologies if I misunderstood anything, and please feel free to close this PR if so!

2023-07-22 07:37 UTC, xylar commented
@SimonBoothroyd, I'm not quite sure why that's not happening automatically.  Thank you for making the PR.

2023-07-22 07:37 UTC, xylar approved these changes

2023-07-24 12:58 UTC, jaimergp commented
There's an ongoing migration for this pin: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/netcdf_fortran46.yaml

There are 4 feedstocks pending: https://conda-forge.org/status/#netcdf_fortran46

- https://github.com/conda-forge/summa-feedstock/pull/7
- https://github.com/conda-forge/mizuroute-feedstock/pull/5
- https://github.com/conda-forge/siesta-feedstock/pull/32
- https://github.com/conda-forge/yambo-feedstock/pull/16

The global pin will be updated once those PRs are merged and the migration can be considered "closed".

2023-07-24 13:53 UTC, xylar commented
Oh, sorry, thanks for pointing that out @jaimergp.  I didn't pay enough attention.

@SimonBoothroyd, we don't actually just change the pin like in this PR.  Instead, we create a migrator and that will gradually work its way through the dependency chain so things don't get broken or unsovlable.

If the migrator hasn't reached your package yet, it's presumably because one of your dependencies hasn't been migrated yet. You'll have to track it down by looking at https://conda-forge.org/status/#netcdf_fortran46

2023-07-24 13:54 UTC, xylar requested changes
We don't want to just update the pin like in this PR, sorry for the confusion.

2023-07-24 16:51 UTC, hmaarrfk commented
i've been calling "soft-close". seems ok given the migration progress

2023-07-24 16:51 UTC, merged