Remove completed migrations
conda-forge/conda-forge-pinning-feedstock pull request #852
Opened 2020-10-11 18:42 UTC by isuruf

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2020-10-11 18:42 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-10-11 18:44 UTC, beckermr requested changes
This is a bug in the bot. Please leave these so I can test the fix.

2020-10-11 18:45 UTC, beckermr commented
See this PR: https://github.com/regro/cf-scripts/pull/1203

2020-10-15 02:35 UTC, jakirkham commented
Looks like the `krb` migration and `nccl` migration were both closed out ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/854 ) ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/855 ) by the bot. So the fix seemed to work there.

Though I don't see one for `r-base`. Are we missing that or are we just opting to remove it manually?

2021-03-09 16:20 UTC, closed without merging