Zip `cdt_name` with `docker_image`
conda-forge/conda-forge-pinning-feedstock pull request #867
Opened 2020-10-15 05:06 UTC by jakirkham

To make sure that we get CDT's compatible with the OS of the Docker image used, specify `cdt_name` for each `docker_image` and zip them together. This will make sure that we get CentOS 7 CDTs on CentOS 7 images and CentOS 6 CDTs on CentOS 6 images.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2020-10-15 05:06 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-10-15 11:40 UTC, beckermr requested changes
We need to edit the docs on using centos7 to add this entry to the cbc example there. Also, this will break rendering for those feedstocks. I think that is ok, but others should weight in.

2020-10-15 16:17 UTC, jakirkham commented
Why would it break things? It seems one would need to add `docker_image` and `cdt_name` anyways, right? I suppose now one might need `cuda_compiler_version` as `None`. Is there anything else I'm missing here?

2020-10-15 16:19 UTC, beckermr commented
See here: https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7

People have already been using the docs here. If we change the global pinnings file, they will need to change their stub.

2020-10-15 16:25 UTC, jakirkham commented
Do CDT's work with that currently? If so, how is `cdt_name` configured correctly?

2020-10-15 16:27 UTC, beckermr commented
You are correct. The docs we have won't work with CDTs. Your change here is the correct answer. I am just wondering what we should do, if anything, about ppl using centos 7 already. It could be that making an announcement with the change is sufficient.

2020-10-15 18:23 UTC, jakirkham commented
Ah ok. FWIW would have been happy to be wrong and there to be an even simpler path 😉 Wasn't totally sure I was overcomplicating things 😄 

Yeah updating the docs sounds good. Do we have an existing CentOS 7 announcement somewhere? If so, what did we use?

2020-10-15 18:25 UTC, beckermr commented
I usually just a note to the announcements in the docs when things change. There is one in there. 

cc @conda-forge/core You all ok with this?

2020-10-15 18:34 UTC, isuruf commented
How many feedstocks are going to get affected? Can we send PRs?

2020-10-15 18:38 UTC, beckermr commented
> How many feedstocks are going to get affected? Can we send PRs?

It cannot be more than a handful I'd guess. We can definitely send PRs if we think it matters.

2020-10-15 20:06 UTC, jakirkham commented
Happy to help send PRs 🙂

2020-10-15 20:07 UTC, jakirkham commented
> I usually just a note to the announcements in the docs when things change. There is one in there.

Yeah no disagreement. Just asking so that we can reuse the same channels of communication 😉

2020-10-17 11:35 UTC, beckermr commented
here is everything that is using this

```
(base) clarence:feedstocks beckermr$ grep -C 3 "cuda_compiler_version" */recipe/conda_build*
austin/recipe/conda_build_config.yaml:cuda_compiler_version:                    # [linux64]
austin/recipe/conda_build_config.yaml-  - None                                  # [linux64]
austin/recipe/conda_build_config.yaml-docker_image:                             # [linux64]
austin/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
--
--
conda-forge-pinning/recipe/conda_build_config.yaml-
conda-forge-pinning/recipe/conda_build_config.yaml-cuda_compiler:                 # [linux64]
conda-forge-pinning/recipe/conda_build_config.yaml-  - nvcc                       # [linux64]
conda-forge-pinning/recipe/conda_build_config.yaml:cuda_compiler_version:
conda-forge-pinning/recipe/conda_build_config.yaml-  - None
conda-forge-pinning/recipe/conda_build_config.yaml-  - 9.2                        # [linux64]
conda-forge-pinning/recipe/conda_build_config.yaml-  - 10.0                       # [linux64]
--
--
conda-forge-pinning/recipe/conda_build_config.yaml-    - numpy
conda-forge-pinning/recipe/conda_build_config.yaml-    - python_impl
conda-forge-pinning/recipe/conda_build_config.yaml-  -                             # [(os.environ.get("CONFIG_VERSION", "1") == "1" and linux64) or os.environ.get("BUILD_PLATFORM") == "linux-64"]
conda-forge-pinning/recipe/conda_build_config.yaml:    - cuda_compiler_version     # [(os.environ.get("CONFIG_VERSION", "1") == "1" and linux64) or os.environ.get("BUILD_PLATFORM") == "linux-64"]
conda-forge-pinning/recipe/conda_build_config.yaml-    - docker_image              # [(os.environ.get("CONFIG_VERSION", "1") == "1" and linux64) or os.environ.get("BUILD_PLATFORM") == "linux-64"]
conda-forge-pinning/recipe/conda_build_config.yaml-
conda-forge-pinning/recipe/conda_build_config.yaml-# aarch64 specifics because conda-build sets many things to centos 6
--
--
cudatoolkit/recipe/conda_build_config.yaml:cuda_compiler_version:                  # [linux64]
cudatoolkit/recipe/conda_build_config.yaml-  - None                                # [linux64]
cudatoolkit/recipe/conda_build_config.yaml-docker_image:                           # [linux64]
cudatoolkit/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64  # [linux64]
--
--
faiss-split/recipe/conda_build_config.yaml:cuda_compiler_version:
faiss-split/recipe/conda_build_config.yaml-- None                         # [not linux]
--
--
firefox/recipe/conda_build_config.yaml:cuda_compiler_version:                    # [linux64]
firefox/recipe/conda_build_config.yaml-  - None                                  # [linux64]
firefox/recipe/conda_build_config.yaml-docker_image:                             # [linux64]
firefox/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
--
--
geckodriver/recipe/conda_build_config.yaml:cuda_compiler_version:                    # [linux64]
geckodriver/recipe/conda_build_config.yaml-  - None                                  # [linux64]
geckodriver/recipe/conda_build_config.yaml-docker_image:                             # [linux64]
geckodriver/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
--
--
htcondor/recipe/conda_build_config.yaml:cuda_compiler_version:                    # [linux64]
htcondor/recipe/conda_build_config.yaml-  - None                                  # [linux64]
htcondor/recipe/conda_build_config.yaml-docker_image:                             # [linux64]
htcondor/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
--
--
htmap/recipe/conda_build_config.yaml:cuda_compiler_version:                    # [linux64]
htmap/recipe/conda_build_config.yaml-  - None                                  # [linux64]
htmap/recipe/conda_build_config.yaml-docker_image:                             # [linux64]
htmap/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
--
--
libtike-cufft/recipe/conda_build_config.yaml:cuda_compiler_version:         # [linux64]
libtike-cufft/recipe/conda_build_config.yaml-  - None                       # [linux64]
libtike-cufft/recipe/conda_build_config.yaml-  - 9.2                        # [linux64]
libtike-cufft/recipe/conda_build_config.yaml-  - 10.0                       # [linux64]
--
--
omniscidb/recipe/conda_build_config.yaml-  - go-cgo
omniscidb/recipe/conda_build_config.yaml-cuda_compiler:
omniscidb/recipe/conda_build_config.yaml-  - nvcc
omniscidb/recipe/conda_build_config.yaml:cuda_compiler_version:
omniscidb/recipe/conda_build_config.yaml-  - None
omniscidb/recipe/conda_build_config.yaml-  - 10.1
omniscidb/recipe/conda_build_config.yaml-docker_image:
--
--
omniscidb/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-comp7
omniscidb/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cuda:10.1
omniscidb/recipe/conda_build_config.yaml-zip_keys:
omniscidb/recipe/conda_build_config.yaml:  - - cuda_compiler_version
omniscidb/recipe/conda_build_config.yaml-    - docker_image
omniscidb/recipe/conda_build_config.yaml-boost_cpp:
omniscidb/recipe/conda_build_config.yaml-  - 1.72
--
--
py-spy/recipe/conda_build_config.yaml:cuda_compiler_version:                    # [linux64]
py-spy/recipe/conda_build_config.yaml-  - None                                  # [linux64]
py-spy/recipe/conda_build_config.yaml-docker_image:                             # [linux64]
py-spy/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
--
--
pyfuse3/recipe/conda_build_config.yaml:cuda_compiler_version:                    # [linux64]
pyfuse3/recipe/conda_build_config.yaml-  - None                                  # [linux64]
pyfuse3/recipe/conda_build_config.yaml-docker_image:                             # [linux64]
pyfuse3/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
--
--
rubinenv/recipe/conda_build_config.yaml:cuda_compiler_version:                    # [linux64]
rubinenv/recipe/conda_build_config.yaml-  - None                                  # [linux64]
rubinenv/recipe/conda_build_config.yaml-docker_image:                             # [linux64]
rubinenv/recipe/conda_build_config.yaml-  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
```

2020-10-19 20:16 UTC, jakirkham commented
So what would be the next step. Submit PRs to all of these repos?

2020-10-19 20:21 UTC, beckermr commented
> So what would be the next step. Submit PRs to all of these repos?

Yup. To be clear:

1. submit PRs to the above
2. submit a PR to the docs repo
3. merge this PR and that from 2

2020-10-19 22:56 UTC, jakirkham commented
Just a note, there is only 1 `omniscidb` (2 other related feedstocks with similar names are archived). Also `libtike-cufft` was recently archived.

2020-10-19 23:56 UTC, jakirkham commented
Outside the caveats noted above ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/867#issuecomment-712485855 ), have submitted PRs to update the feedstocks we found and xref'd back to this PR.

2020-10-19 23:59 UTC, beckermr commented
Great. I can do the docs pr later. I'm gonna merge this now.

2020-10-20 00:00 UTC, merged

2020-10-20 00:02 UTC, jakirkham commented
Thank Matt! Actually have PR ( https://github.com/conda-forge/conda-forge.github.io/pull/1169 ) for the docs up already. Though if there is anything I'm missing, please feel free to mention there.

2020-10-20 00:07 UTC, beckermr commented
Great! Thank you!

2020-10-20 00:21 UTC, jakirkham commented
Ofc! 😄

2020-10-20 00:47 UTC, isuruf commented
Need to fix https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/pypy.yaml too

2020-10-20 00:52 UTC, beckermr commented
Ahhh thank you. I am on a phone but can fix later

2020-10-20 00:53 UTC, isuruf commented
Thanks. I'm going to move the latest build to broken until that is fixed.

2020-10-20 01:18 UTC, jakirkham commented
Looks like this is being handled in PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/879 ). Thanks Matt! 😄

2021-01-06 23:34 UTC, jakirkham commented
Resubmitted as PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1076 ).